package com.visvise.sdk.models;

import com.google.gson.annotations.SerializedName;

import java.util.HashMap;
import java.util.Map;

/**
 * MotionSegment represents a single segment in a text-to-motion timeline.
 *
 * <p>It mirrors the backend MotionSegment protocol. The {@code index} field is
 * server-internal (generated by the server in array order) and is not exposed
 * by the SDK.</p>
 *
 * <ul>
 *   <li>{@code text}: segment action description (required).</li>
 *   <li>{@code numFrames} / {@code duration}: segment duration; at least one must
 *       be provided (when both are set, {@code numFrames} takes priority).</li>
 *   <li>{@code overlapFramesWithPrev} / {@code overlapDurationWithPrev}: transition
 *       with the previous segment (not needed for the first segment).</li>
 * </ul>
 */
public class MotionSegment {
    @SerializedName("text")
    private String text;

    @SerializedName("num_frames")
    private Integer numFrames;

    @SerializedName("duration")
    private Double duration;

    @SerializedName("overlap_frames_with_prev")
    private Integer overlapFramesWithPrev;

    @SerializedName("overlap_duration_with_prev")
    private Double overlapDurationWithPrev;

    public MotionSegment() {
    }

    public MotionSegment(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }

    public MotionSegment setText(String text) {
        this.text = text;
        return this;
    }

    public Integer getNumFrames() {
        return numFrames;
    }

    public MotionSegment setNumFrames(Integer numFrames) {
        this.numFrames = numFrames;
        return this;
    }

    public Double getDuration() {
        return duration;
    }

    public MotionSegment setDuration(Double duration) {
        this.duration = duration;
        return this;
    }

    public Integer getOverlapFramesWithPrev() {
        return overlapFramesWithPrev;
    }

    public MotionSegment setOverlapFramesWithPrev(Integer overlapFramesWithPrev) {
        this.overlapFramesWithPrev = overlapFramesWithPrev;
        return this;
    }

    public Double getOverlapDurationWithPrev() {
        return overlapDurationWithPrev;
    }

    public MotionSegment setOverlapDurationWithPrev(Double overlapDurationWithPrev) {
        this.overlapDurationWithPrev = overlapDurationWithPrev;
        return this;
    }

    /**
     * Converts MotionSegment to Map for JSON serialization, omitting null
     * optional fields.
     */
    public Map<String, Object> toMap() {
        Map<String, Object> m = new HashMap<>();
        m.put("text", text);
        if (numFrames != null) {
            m.put("num_frames", numFrames);
        }
        if (duration != null) {
            m.put("duration", duration);
        }
        if (overlapFramesWithPrev != null) {
            m.put("overlap_frames_with_prev", overlapFramesWithPrev);
        }
        if (overlapDurationWithPrev != null) {
            m.put("overlap_duration_with_prev", overlapDurationWithPrev);
        }
        return m;
    }
}
